## Association Rule Mining Using Apriori Algorithm

In [1]:
pip install mlxtend

Collecting mlxtend
  Downloading mlxtend-0.23.3-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: scipy>=1.2.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (1.15.0)
Requirement already satisfied: numpy>=1.16.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (2.2.0)
Requirement already satisfied: pandas>=0.24.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (2.2.3)
Requirement already satisfied: scikit-learn>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (1.6.0)
Requirement already satisfied: matplotlib>=3.0.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (3.10.0)
Requirement already satisfied: joblib>=0.13.2 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from mlxtend) (1.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.3.1)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (1.4.8)
Requirement already satisfied: packaging>=20.0 in /Users/farhoudkhoshnoud/Library/Python/3.12/lib/python/site-packages (from matplotlib>=3.0.0->mlxtend) (24.2)
Requirement already satisfied: pillow>=8 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (11.0.0)
Requirement already satisfied: pyparsing>=2.3.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from matplotlib>=3.0.0->mlxtend) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in /Users/farhoudkhoshnoud/Library/Python/3.12/lib/python/site-packages (from matplotlib>=3.0.0->mlxtend) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from pandas>=0.24.2->mlxtend) (2024.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages (from scikit-learn>=1.3.1->mlxtend) (3.5.0)
Requirement already satisfied: six>=1.5 in /Users/farhoudkhoshnoud/Library/Python/3.12/lib/python/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->mlxtend) (1.16.0)
Downloading mlxtend-0.23.3-py3-none-any.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 146.7 kB/s eta 0:00:0000:0100:01
Installing collected packages: mlxtend
Successfully installed mlxtend-0.23.3

[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
# data = pd.read_csv('/workspaces/python-for-data-science-and-machine-learning-essential-training-part-2-3016934/data/groceries.csv')
data = pd.read_csv('../data/groceries.csv')

In [4]:
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

In [5]:
baskets_sets = data.stack().str.get_dummies().groupby(level=0).sum()

In [6]:
baskets_sets.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [7]:
baskets_sets_bool = baskets_sets.astype(bool)
apriori(baskets_sets_bool, min_support=0.02)

      support         itemsets
0    0.028155              (1)
1    0.054369              (8)
2    0.032039              (9)
3    0.027508             (10)
4    0.072492             (11)
..        ...              ...
105  0.022977       (154, 163)
106  0.033981       (162, 158)
107  0.055987       (162, 163)
108  0.022977  (121, 162, 101)
109  0.022977  (162, 163, 101)

[110 rows x 2 columns]

In [8]:
baskets_sets_bool = baskets_sets.astype(bool)
apriori(baskets_sets_bool, min_support=0.02, use_colnames=True)

      support                                         itemsets
0    0.028155                                       (UHT-milk)
1    0.054369                                           (beef)
2    0.032039                                        (berries)
3    0.027508                                      (beverages)
4    0.072492                                   (bottled beer)
..        ...                                              ...
105  0.022977                         (yogurt, tropical fruit)
106  0.033981                 (whipped/sour cream, whole milk)
107  0.055987                             (yogurt, whole milk)
108  0.022977  (other vegetables, root vegetables, whole milk)
109  0.022977           (yogurt, other vegetables, whole milk)

[110 rows x 2 columns]

In [9]:
df_combo = baskets_sets.astype(bool)

frequent_itemsets = apriori(df_combo, min_support=0.002, use_colnames=True)

frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

frequent_itemsets

       support                                           itemsets  length
0     0.007120                            (Instant food products)       1
1     0.028155                                         (UHT-milk)       1
2     0.002913                                 (abrasive cleaner)       1
3     0.003560                                 (artif. sweetener)       1
4     0.014887                                    (baking powder)       1
...        ...                                                ...     ...
2313  0.002265  (other vegetables, root vegetables, whole milk...       5
2314  0.002589  (other vegetables, whole milk, yogurt, whipped...       5
2315  0.002265  (other vegetables, whole milk, whipped/sour cr...       5
2316  0.002265  (tropical fruit, other vegetables, root vegeta...       5
2317  0.002265  (tropical fruit, other vegetables, whole milk,...       5

[2318 rows x 3 columns]

In [14]:
frequent_itemsets[(frequent_itemsets['length']>=3)]

       support                                           itemsets  length
1260  0.002589        (UHT-milk, other vegetables, bottled water)       3
1261  0.002265                    (UHT-milk, soda, bottled water)       3
1262  0.002589      (other vegetables, baking powder, whole milk)       3
1263  0.002265    (whipped/sour cream, baking powder, whole milk)       3
1264  0.002589                        (whole milk, beef, berries)       3
...        ...                                                ...     ...
2313  0.002265  (other vegetables, root vegetables, whole milk...       5
2314  0.002589  (other vegetables, whole milk, yogurt, whipped...       5
2315  0.002265  (other vegetables, whole milk, whipped/sour cr...       5
2316  0.002265  (tropical fruit, other vegetables, root vegeta...       5
2317  0.002265  (tropical fruit, other vegetables, whole milk,...       5

[1058 rows x 3 columns]

In [15]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.9)
rules.head()

TypeError: association_rules() missing 1 required positional argument: 'num_itemsets'

In [12]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

TypeError: association_rules() missing 1 required positional argument: 'num_itemsets'

In [13]:
rules[(rules['lift']>=5) & (rules['confidence']>= 0.8)]

NameError: name 'rules' is not defined